server:  
 port: 7002

eureka: 
 instance: 
  hostname: localhost:7002
 client:
  register-with-eureka: false
  fetch-register: false
  service-url: 
    defaultZone: http://localhost:7002/eureka/	
