server:
 port: 3344

spring:
 application:
  name: cloud-config-server
 cloud:
  config:
   server:
    git:
     uri: https://github.com/xjwgithub/springCloud-config.git
     search-paths: 
       - springCloud-config
     username: xjwgithub
     password: xjwgithub12345
   label: master 

eureka: 
 client:
  register-with-eureka: true
  fetch-register: true
  service-url: 
   defaultZone: http://localhost:7002/eureka/