server: 
 port: 8004

spring: 
 application: 
  name: order-consumer-consul
 cloud: 
  consul: 
   host: localhost
   port: 8500
   discovery:
    service-name: ${spring.application.name}
#暴露端口
management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字